version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the frontend application...
      - npm run build
artifacts:
  files:
    - '**/*' 
  base-directory: build
cache:
  paths:
    - node_modules/**/* 
